### ISSUE TITLE
I can't find autogen.cpp and autogen.gml

### ISSUE THREAD

**Issue by fengfeng16** [YAL-GameMaker/Apollo#2]
1>Running pre-build for Release
1>Running GmlCppExtFuncs...
1>Called from ? line 1
1>Called from CppGen.hx line 148
1>Called from CppGen.hx line 112
1>Called from D:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx line 29
1>Uncaught exception - [file_contents,Studio]

Build.md says “If you have correctly set up `GmxGen` and `GmlCppExtFuncs`,
the project will generate the `autogen.gml` files for GML<->C++ interop during pre-build”
But I just got a bunch of errors like this and the error that autogen.cpp cannot be found

**Comment by YellowAfterlife** [comment]
What's the full path to the project like?

**Comment by fengfeng16** [comment]
> 项目的完整路径是什么样的？

D:\Visual Studio Project\Apollo-main\Apollo.sln

**Comment by YellowAfterlife** [comment]
I can probably fix that, but for now try removing the spaces from the folder name ("Visual_Studio_Project" instead of "Visual Studio Project")

**Comment by fengfeng16** [comment]
> 我可能可以解决这个问题，但现在尝试从文件夹名中删除空间（“Visual_Studio_Project”而不是“Visual Studio Project”）

Thanks for the help, I have successfully build！

**Comment by fengfeng16** [comment]
> I can probably fix that, but for now try removing the spaces from the folder name ("Visual_Studio_Project" instead of "Visual Studio Project")

excuse me,When I use this extension, I can't load Lua code in a non English path through lua_add_file. What can I do to make the extension support this?

**Comment by YellowAfterlife** [comment]
> I can't load lua files with non-English paths through lua_add_file，Will the extension fix the problem that non-English paths cannot load lua files in the future?

I'm yet to find the "expected" solution to this problem - people [appear to](http://lua-users.org/lists/lua-l/2019-01/msg00077.html) commonly rewrite a part of Lua code to use different functions on Windows, but that creates a number of other problems.

**Comment by fengfeng16** [comment]
> > I can't load lua files with non-English paths through lua_add_file，Will the extension fix the problem that non-English paths cannot load lua files in the future?
> 
> I'm yet to find the "expected" solution to this problem - people [appear to](http://lua-users.org/lists/lua-l/2019-01/msg00077.html) commonly rewrite a part of Lua code to use different functions on Windows, but that creates a number of other problems.

I got it, thank you very much for your help
